spring.application.name=backend
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hoa_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
# 'update' will automatically create/update your tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Boots Password
spring.security.user.name=admin
spring.security.user.password=363966246Fav25

# Change port to 8081 to avoid conflict with Apache/XAMPP
server.port=8081